#!/bin/bash
echo "============================================"
echo "  My Team Budget - Aucune installation requise !"
echo "============================================"
echo ""
echo "  Le frontend est pré-buildé et le serveur"
echo "  utilise uniquement Python standard (built-in)."
echo ""
echo "  Pour lancer l'application :"
echo "    python3 server.py"
echo ""
echo "  Puis ouvrir : http://localhost:5001"
echo ""
